name: client
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  dio: ^5.1.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_native_splash: ^1.2.0
  flutter_launcher_icons: 
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter_icons:
  image_path_android: "assets/images/launcher_icon.png"
  image_path_ios: "assets/images/launcher_icon.png"
  ios: true
  android: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/images/launcher_icon.png


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/